server:
  port: 9999

spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/mail?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
      username: root
      password: 12345678
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/mail_bak?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
      username: root
      password: 12345678

#mybaits配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
