server:
  port: 8081


custom:
  starter:
    enabled: true
    students:
      - id: 100
        name: s100
      - id: 101
        name: s101
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

