server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/stock?useUnicode=true&characterEncoding=utf8
    username: root
    password:

